export default {
  ADD_RECORD: 'ADD_RECORD',
  ADD: 'ADD',
  SET_RECORDS: 'SET_RECORDS',
  SET_RECORD: 'SET_RECORD',
  FETCH_RECORDS: 'FETCH_RECORDS',
  FETCH_RECORD: 'FETCH_RECORD',
  DELETE_RECORD: 'DELETE_RECORD',
};
